from K_types import Injection, SearchType, ChangeType, Search, Change

injections = [
    Injection(
        Search(
        file_path="config-keys.def",
        search_type=SearchType.TEXT,
        search_query="<Key-F5>",
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query="k-upload=<Key-F7>\nk-download=<Key-F8>",
            limit=None
        )
    ),
    Injection(
        Search(
        file_path="config.py",
        search_type=SearchType.TEXT,
        search_query="<Key-F5>",
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query="'<<k-upload>>': ['<Key-F7>'],\n'<<k-download>>': ['<Key-F8>'],"
        )
    ),
    Injection(
        Search(
        file_path="editor.py",
        search_type=SearchType.BEGINNING,
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query="import k_main\nimport threading"
        )
    ),
    Injection(
        Search(
        file_path="editor.py",
        search_type=SearchType.TEXT,
        search_query="ScriptBinding(self)"
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query='        self.scriptbinder_k = scriptbinding\n        text.bind("<<k-upload>>", self.upload_k)\n        text.bind("<<k-upload>>", self.download_k)'
        )
    ),
    Injection(
        Search(
        file_path="editor.py",
        search_type=SearchType.TEXT,
        search_query="class EditorWindow:"
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_file_path="K_change_assets/editor_k_part"
        )
    ),
    Injection(
        Search(
        file_path="mainmenu.py",
        search_type=SearchType.BEGINNING
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query="import k_values"
        )
    ),
    Injection(
        Search(
        file_path="mainmenu.py",
        search_type=SearchType.TEXT,
        search_query="<<run-custom>>"
        ),
        Change(
            change_type=ChangeType.ADD_NEXT_LINE,
            change_query="(k_values.f7_title, '<<k-upload>>'),(k_values.f8_title, '<<k-download>>'),"
        )
    ),
    Injection(
        Search(
        file_path="runscript.py",
        search_type=SearchType.TEXT,
        search_query="__name__"
        ),
        Change(
            change_type=ChangeType.ADD_BEFORE_LINE,
            change_query="    def k_is_output_window(self):return isinstance(self.editwin, outwin.OutputWindow)"
        )
    ),
    Injection(
        Search(
            file_path='k_main.py',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/k_main.py'
        )
    ),
    Injection(
        Search(
            file_path='k_networkin.py',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/k_networkin.py'
        )
    ),
    Injection(
        Search(
            file_path='k_server.py',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/k_server.py'
        )
    ),
    Injection(
        Search(
            file_path='k_values.py',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/k_values.py'
        )
    ),
    Injection(
        Search(
            file_path='six.py',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/six.py'
        )
    ),
    Injection(
        Search(
            file_path='pymsgbox',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/pymsgbox'
        )
    ),
    Injection(
        Search(
            file_path='pynput',
            search_type=SearchType.ANY
        ),
        Change(
            change_type=ChangeType.OVERWRITE,
            change_file_path='K_change_assets/pynput'
        )
    ),
]